# Travis CI Configuration File

# Use new Travis container-based infrastructure
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# Tell Travis CI we're using PHP
language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=master
    - WP_VERSION=4.3
    - WP_VERSION=4.2
    - WP_VERSION=4.1
    - WP_VERSION=4.0
    - WP_VERSION=3.9
    - WP_VERSION=3.8

matrix:
  fast_finish: true
  include:
    - php: 5.2
      env: WP_VERSION=master
    - php: nightly
      env: WP_VERSION=master
    - php: hhvm
      env: WP_VERSION=master
  exclude:
    - php: 7.0
      env: WP_VERSION=4.2
    - php: 7.0
      env: WP_VERSION=4.1
    - php: 7.0
      env: WP_VERSION=4.0
    - php: 7.0
      env: WP_VERSION=3.9
    - php: 7.0
      env: WP_VERSION=3.8
  allow_failures:
    - php: nightly
    - php: hhvm

# Clones WordPress and configures our testing environment.
before_script:
    - bash bin/install-wp-tests-travis.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
